project:
  type: website
  output-dir: docs

website:
  title: "Inder Preet"
  site-url: https://www.inderpreet.ie
  navbar:
    left:
      - href: index.qmd
        text: About
#      - index.qmd
      - portfolio.qmd
      - blog.qmd
      - href: Inder_CV.pdf
        target: _blank
        text: Curriculum Vitae
#      - services.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false




