project:
  type: website
  output-dir: docs

website:
  title: "KabroAI"
  site-url: https://www.kabroai.ie/
  navbar:
    left:
      - href: index.qmd
        text: About
#      - index.qmd
      - portfolio.qmd
      - blog.qmd
      - href: Inder_CV.pdf
        target: _blank
        text: Curriculum Vitae
#      - services.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false




