project:
  type: website
  output-dir: docs

website:
  title: "Inder Preet"
  site-url: https://www.inderpreet.ie
  navbar:
    left:
      - href: index.qmd
        text: About
#      - index.qmd
      - portfolio.qmd
      - blog.qmd
      - text: "Publications"
        href: media.qmd
#      - text: "Life Logging"
#        href: life_logging_app.qmd
#      - href: Inder_CV.pdf
#        target: _blank
#        text: Curriculum Vitae

#      - services.qmd

execute:
  cache: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false




